fingerprint_method: 'seed'
cached_fingerprints_path: 'cache/seed/seed_fingerprints.pth'
re_fingerprinting: False
fingerprint_type: 'white-box'
seed: 42

random_input_path: 'cache/seed/fingerprint_input'
num_sequences: 2000
seq_length: 1024
output_type: 'hidden_states'
batch_size: 32
ratio_k: 0.25
normalize: 'softmax_T10'
num_random_baseline_trials: 10
